// actionTypes.ts

// for toollist
export const SHOW_TOOLBUTTON = 'SHOW_TOOLBUTTON';
export const SET_TOOLBUTTON_POSITION = 'SET_TOOLBUTTON_POSITION';

// for node
export const SET_NODE_EDITING = 'SET_NODE_EDITING';
export const SET_NODE_NAME = 'SET_NODE_NAME';
export const SHOW_NODE_SETTINGS = 'SHOW_NODE_SETTINGS';
export const HIDE_NODE_SETTINGS = 'HIDE_NODE_SETTINGS';
export const SET_LAST_DESELECTED_NODE_ID = 'SET_LAST_DESELECTED_NODE_ID';
export const SET_SELECTED_NODE = 'SET_SELECTED_NODE';

// for colorpicker
export const SET_COLOR = 'SET_COLOR';
export const SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR';
export const SET_PRIMARY_COLORS = 'SET_PRIMARY_COLORS';
export const INCREMENT_COLOR_FREQUENCY = 'INCREMENT_COLOR_FREQUENCY';
export const UPDATE_PRIMARY_COLORS = 'UPDATE_PRIMARY_COLORS';
export const SHOW_COLOR_PICKER = 'SHOW_COLOR_PICKER';
export const HIDE_COLOR_PICKER = 'HIDE_COLOR_PICKER';
export const SHOW_BACKGROUND_COLOR_PICKER = 'SHOW_BACKGROUND_COLOR_PICKER';
export const HIDE_BACKGROUND_COLOR_PICKER = 'HIDE_BACKGROUND_COLOR_PICKER';
export const INCREMENT_BACKGROUND_COLOR_FREQUENCY = 'INCREMENT_BACKGROUND_COLOR_FREQUENCY';
export const UPDATE_BACKGROUND_PRIMARY_COLORS = 'UPDATE_BACKGROUND_PRIMARY_COLORS';
export const SHOW_PICKER = 'SHOW_PICKER';
export const HIDE_PICKER = 'HIDE_PICKER';
export const TOGGLE_PICKER = 'TOGGLE_PICKER';
export const SET_POPUP_POSITION = 'SET_POPUP_POSITION';

// for edge
export const ADD_EDGE = 'ADD_EDGE';
export const START_EDGE_CREATION = 'START_EDGE_CREATION';
export const END_EDGE_CREATION = 'END_EDGE_CREATION';
export const UPDATE_HANDLE_POSITION = 'UPDATE_HANDLE_POSITION';
export const TOGGLE_EDGE_CREATION_MODE = 'TOGGLE_EDGE_CREATION_MODE ';

// for searchbar
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const UPDATE_SEARCH_BAR_POSITION = 'UPDATE_SEARCH_BAR_POSITION';
export const SET_FOCUS = 'SET_FOCUS';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';


// for polarnode
export const SELECT_POLAR_NODE = 'SELECT_POLAR_NODE';
export const SET_NODE_DRAG_DIFFERENCE = 'SET_NODE_DRAG_DIFFERENCE';
export const UPDATE_DRAGGED_POSITION = 'UPDATE_DRAGGED_POSITION';
export const CENTER_POLAR_NODE = 'CENTER_POLAR_NODE '
export const UPDATE_QUERY = 'UPDATE_QUERY';


// for polarNodeEdge
export const ADD_POLAREDGE_INFO = 'ADD_POLAREDGE_INFO';
export const CLEAR_POLAREDGE_INFO = "CLEAR_POLAREDGE_INFO";
